language: go
go:
  - "1.8"

git:
  depth: 10

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install node -y
  - go get -u -v github.com/gohugoio/hugo
  - npm install -g gulp

install:
  - npm install

script:
  - gulp sass data && hugo

before_deploy:
  - gulp sass data && hugo

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: public
    target_branch: master
    on:
      branch: hugo-site
