# This is a basic workflow to help you get started with Actions

name: Build Cards

# Controls when the action will run. 
on:
  workflow_dispatch:
  schedule:
    - cron: '* */1 * * *'
  push:
    branches: [ hugo-site ]
  pull_request:
    branches: [ hugo-site ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: after npm
        run: |
          #go get -u -v github.com/gohugoio/hugo
          npm install -g gulp
          #gulp sass data && hugo
